
= Pflichtenheft

=== Ausgangslage
Projektbezeichnung: MiniHome +
Auftraggeber: HTBLA Leonding

== Zielsetzung
Ziel des Projekts soll sein z.B. das Stromsparen spaßig und wettbewerblich zu machen. Auch sollen Abhängigkeiten von Dritten beseitigt werden können, in dem MiniHome, ähnlich wie bei Docker, als selbstständige Einheit exportiert werden kann.
Das Projekt "MiniHome" zielt außerdem darauf ab eine große Breite an bestehenden Sensoren und Microcontroller in einem Dashboard zu vereinen und ein Wettbewerbsgefühl zwischen den Teilnehmern zu erschaffen (Vergleichen des Stromverbrauchs, ...).

== Anforderungen
Das Endergebnis des Projekts soll eine eigenständige Einheit sein. Das Dashboard und die Sammlung historischer Sensor Daten soll unabhängig von zentralen Servern laufen können, sollte dies erwünscht sein.

Oberflächlich betrachtet soll das Endergebnis ein Dashboard sein, in welchem man Daten von vom Nutzer gruppierten Sensoren auslesen kann. Hier soll die Möglichkeit dazu bestehen die Sensoren nach Lust und Laune hinzuzufügen und zu entfernen. Auch soll der Nutzer die Möglichkeit dazu haben, selbst programmierte und/oder gebaute sensoren hinzuzufügen (DYI Faktor). Sollte es erwünscht sein kann der Nutzer sich außerdem für eine Rangliste registrieren, bei welcher der Stromverbrauch mit dem von anderen verglichen wird. Bei der Platzierung sollten Alter und Menge der Mitbewohner mit eingerechnet werden, um ein faires Ergebnis zu garantieren.

Wichtig für die fairness ist vor allem, dass die Rangliste in mehreren Kategorien existiert. Also z.B. Stromverbrauch absolut, Stromverbrauch pro m^2 oder Stromverbrauch pro Person.

=== Anforderungen an das System
Die Systemanforderungen sind niedrig. Es wird davon ausgegangen, dass ein VPS Server mit 4vCPUs und ~6GB Ram ausreicht.
Sollte mehr benötigt werden, muss horizontal erweitert werden. Dies wäre durch sharding möglich.

== Mengengerüst
Die projizierten Datenmengen sind stark von dem gewählten deployment Typen abhängig.
Wenn der Nutzer sich für ein self-contained deployment auf einem eigenen Server entscheidet, beschränkt sich die Menge an Daten die verarbeitet werden müseen rein auf die Nutzung des Individuums.
Sollte der Nutzer diese Möglichkeit jedoch nicht haben wird sein Dashboard als container auf einem oder mehreren Servern (Sharding) als container gehostet und zur Verfügung gestellt. In diesem Fall entstehen größere Ansammlungen an Daten.
Durch sharding würden allerdings die Requests so aufgeteilt werden, dass die Last minimal wäre.
[%hardbreaks]
Man kann aber folgendes schätzen:
1 Datensatz (z.B Raumtemperatur) -> bis zu 360 Bytes
[%hardbreaks]
Bei 1 Datensatz:
Unter Annahme von Abfragen alle 15min -> 34500 Bytes (34.5KB) am Tag
Pro Monat -> 1.035MB
Pro Jahr -> 12.45MB
Zeit bis 1GB -> ~82.2 Jahre
[%hardbreaks]
Bei 10 Datensätzen:
Pro Tag -> 345KB
Pro Monat -> 10.35MB
Pro Jahr -> 124.5MB
Zeit bis 1GB -> ~8.22 Jahre

== Administratives
Budgetrahmen: 6€/Monat +
Abgabetermin: Unbekannt. Vor Notenschluss +
Team: Tsolmonbat Batbold, Alexander Resch, Elija Lambourne. +
Eine "Teamleitung" ist nicht vorgesehen und nicht erwünscht.

