= Pflichtenheft

ß

=== Ausgangslage
Projektbezeichnung: MiniHome \n herererrrr
Auftraggeber: HTBLA Leonding

== Zielsetzung
Ziel des Projekts soll sein z.B. das Stromsparen spaßig und wettbewerblich zu machen. Auch sollen Abhängigkeiten von Dritten beseitigt werden können, in dem MiniHome, ähnlich wie bei Docker, als selbstständige Einheit exportiert werden kann.
Das Projekt "MiniHome" zielt außerdem darauf ab eine große Breite an bestehenden Sensoren und Microcontrollern in einem Dashboard zu vereinen und ein Wettbewerbsgefühl zwischen den Teilnehmern zu erschaffen (Vegleichen des Stromverbrauchs, ...).

== Anforderungen
Das Endergebnis des Projekts soll eine eigenständige Einheit sein. Das Dashboard und die Sammlung historischer Sensor Daten soll unabhängig von zentralen Servern laufen können, sollte dies erwünscht sein.

Oberflächlich betrachtet soll das Endergebnis ein Dashboard sein, in welchem man Daten von vom Nutzer gruppierten Sensoren auslesen kann. Hier soll die Möglichkeit dazu bestehen die Sensoren nach Lust und Laune hinzuzufügen und zu entfernen. Auch soll der Nutzer die Möglichkeit dazu haben, selbst programmierte und/oder gebaute sensoren hinzuzufügen (DYI Faktor). Sollte es erwünscht sein kann der Nutzer sich außerdem für eine Rangliste registrieren, bei welcher der Stromverbrauch mit dem von anderen verglichen wird. Bei der Platzierung sollten Alter und Menge der Mitbewohner mit eingerechnet werden um ein faires Ergebnis zu garantieren.

Wichtig für die fairness ist vor allem, dass die Rangliste in mehreren Kategorien existiert. Also z.B. Stromverbrauch absolut, Stromverbrauch pro m^2 oder Stromverbrauch pro Person.

== Mengengerüst

Die projizierten Datenmengen sind stark von dem gewählten deployment Typen abhängig.
Wenn der Nutzer sich für ein self-contained deployment auf einem eigenen Server entscheidet, beschränkt sich die Menge an Daten die verarbeitet werden müseen rein auf die Nutzung des Individuums.
Sollte der Nutzer diese Möglichkeit jedoch nicht haben wird sein Dashboard als container auf einem oder mehreren Servern (Sharding) als container gehostet und zur Verfügung gestellt. In diesem Fall entstehen größere Ansammlungen an Daten.
Durch sharding würden allerdings die Requests so aufgeteilt werden, dass die Last minimal wäre.
